### ISSUE TITLE
Working with data in PyTorch

### ISSUE THREAD

**Issue by grig-guz** [ubclaunchpad/hermes#10]
We need to check how to set up training and represent the data in PyTorch. Given our data, check out DataLoader class, find out how training is done with it, and write the code to convert our dataset to use it.

**Comment by grig-guz** [comment]
This looks promising:
https://github.com/pytorch/text

**Comment by Teetertater** [comment]
Converted our data input format to hdf5 format. Extended Pytorch Dataset class to plug our data in from the hdf5 file
https://colab.research.google.com/drive/1DDp9Zx88xboExamguYf1h51Ghar_QSTN#scrollTo=XriqX-qlIpFG
