### ISSUE TITLE
Set up JupyterLab

### ISSUE THREAD

**Issue by grig-guz** [ubclaunchpad/hermes#4]
We need Jupyter lab to play with models/data and write clean code on repo.

## Task
1. Harass Bruno ad get us DigitalOcean instance (we are sponsored by them, so we should have a few free droplets, I suppose)
2. Set up JupyterLab server

**Comment by grig-guz** [comment]
We decided to give Colaboratory a try. In case if it's not comfortable to use, we'll go back to this issue.

**Comment by Teetertater** [comment]
Here is a demo colaboratory notebook I've shared
https://drive.google.com/file/d/1vfw6LvDm8hP54VyNekhWIAMJ-y52Qa-q/view?usp=sharing

**Comment by grig-guz** [comment]
@Teetertater can you make it not private?

**Comment by Teetertater** [comment]
done
